name: dev
services:
  frontend:
    extends:
      file: base/docker-compose.yml
      service: frontend

  go.teleport:
    extends:
      file: base/docker-compose.yml
      service: go.teleport

  node:
    container_name: node
    hostname: node
    extends:
      file: base/docker-compose.yml
      service: node
    volumes:
      - ./node/teleport.yaml:/etc/teleport.yaml

networks:
  teleport:
