services:
  go.teleport:
    extends:
      file: base/docker-compose.yml
      service: go.teleport

  node2:
    container_name: node2
    hostname: node2
    extends:
      file: base/docker-compose.yml
      service: node
    volumes:
      - /var/lib/teleport
      - ./node/teleport.yaml:/etc/teleport.yaml

  access-graph:
    extends:
      file: base/docker-compose.yml
      service: access-graph

  db:
    extends:
      file: base/docker-compose.yml
      service: db

networks:
  teleport:
