services:
  beast:
    platform: linux/arm64/v8
    extends:
      file: base/docker-compose.yml
      service: beast
    container_name: beast
    hostname: beast
    volumes:
      - ./teleport/local/teleport.yaml:/etc/teleport.yaml
    networks:
      teleport:
        aliases:
          - beast
          - dumper.beast

  node:
    container_name: node
    hostname: node
    platform: linux/arm64/v8
    extends:
      file: base/docker-compose.yml
      service: node
    volumes:
      - ./data/node:/var/lib/teleport
      - ./node/teleport.yaml:/etc/teleport.yaml

  accessgraph:
    platform: linux/arm64/v8
    extends:
      file: base/docker-compose.yml
      service: accessgraph

  db:
    extends:
      file: base/docker-compose.yml
      service: db

networks:
  teleport:
