services:
  go.teleport:
    extends:
      file: base/docker-compose.yml
      service: go.teleport
    ports:
      - 443:3080

  node:
    container_name: node
    hostname: node
    extends:
      file: base/docker-compose.yml
      service: node
    volumes:
      - ./data/node:/var/lib/teleport
      - ./node/teleport.yaml:/etc/teleport.yaml
