services:
  go.teleport:
    extends:
      file: base/docker-compose.yml
      service: go.teleport
    ports:
      - 443:3080

  node:
    extends:
      file: base/docker-compose.yml
      service: node
