services:
  frontend:
    extends:
      file: base/docker-compose.yml
      service: frontend

  go.teleport:
    extends:
      file: base/docker-compose.yml
      service: go.teleport

  node:
    extends:
      file: base/docker-compose.yml
      service: node

networks:
  teleport:
