services:
  frontend:
    container_name: frontend
    build:
      dockerfile: ../development/frontend/Dockerfile
      context: ../../teleport
    working_dir: ${VITE_CONFIG_DIRECTORY}
    command: pnpm start
    networks:
      - teleport
    ports:
      - 443:3000
    volumes:
      - ../../teleport/web/:/app/web/
      - ../../teleport/gen/proto/ts/:/app/gen/proto/ts/
      - ../../teleport/e/web/:/app/e/web/
      - ../../teleport/lib/srv/desktop/rdp/rdpclient/:/app/lib/srv/desktop/rdp/rdpclient
      - ../certs:/app/certs:ro
      - /usr/local/cargo
    environment:
      NODE_OPTIONS: --max-old-space-size=8192
      PROXY_TARGET: go.teleport:443
      VITE_HTTPS_CERT: /app/certs/server.crt
      VITE_HTTPS_KEY: /app/certs/server.key

  node:
    build:
      dockerfile: development/build/Dockerfile
      context: ../..
      target: static
      args:
        TOOL_FOLDER: ${TOOL_FOLDER}
    volumes:
      - /var/lib/teleport
    networks:
      - teleport

  go.teleport:
    container_name: go.teleport
    hostname: go.teleport
    build:
      dockerfile: development/build/Dockerfile
      context: ../..
      target: live-reload
      args:
        TOOL_FOLDER: ${TOOL_FOLDER}
    working_dir: /app
    command:
      - --build.cmd
      - "go build -buildvcs=false -o tmp/teleport -ldflags '-w -s' -tags 'webassets_embed webassets_ent' ./${TOOL_FOLDER}/teleport"
    networks:
      teleport:
        aliases:
          - go.teleport
          - dumper.go.teleport
    ports:
      - 3080:443
      - 3025:3025
      - 3024:3024
      - 3023:3023
    volumes:
      - ../../teleport:/app/:rw,delegated
      - ../../teleport/webassets/:/app/webassets/
      - /app/tmp
      - /go/pkg/mod
      - /root/.cache/go-build
      - /var/lib/teleport
      - ../build/.air.toml:/app/.air.toml
      - ../teleport/teleport.yaml:/etc/teleport.yaml
      - ${LICENSE_FILE}:/etc/license.pem

networks:
  teleport:
