services:
  frontend:
    container_name: frontend
    build:
      dockerfile: ../development/frontend/Dockerfile
      context: ../../webapps
      target: configs
    working_dir: ${WEBPACK_CONFIG_DIRECTORY}
    command: node /app/packages/build/devserver/index.js --config ${WEBPACK_CONFIG_DIRECTORY}/webpack.dev.config.js --target https://go.teleport/web
    networks:
      - teleport
    ports:
      - 443:8080
      - 8888:8888
    volumes:
      - ../../webapps/node_modules/:/app/node_modules:ro,delegated
      - ../../webapps/packages/:/app/packages
      - ../certs:/app/certs:ro
      - ../data/cache/frontend:/webpack/cache:rw,delegated
    environment:
      NODE_OPTIONS: --max-old-space-size=8192
      WEBPACK_HTTPS_CERT: /app/certs/server.crt
      WEBPACK_HTTPS_KEY: /app/certs/server.key
      WEBPACK_CACHE_DIRECTORY: /webpack/cache
      WEBPACK_ANALYZE_BUNDLE: yes

  node:
    build:
      dockerfile: development/build/Dockerfile
      context: ../..
      target: static
      args:
        TOOL_FOLDER: ${TOOL_FOLDER}
    networks:
      - teleport

  go.teleport:
    container_name: go.teleport
    hostname: go.teleport
    build:
      dockerfile: development/build/Dockerfile
      context: ../..
      target: live-reload
      args:
        TOOL_FOLDER: ${TOOL_FOLDER}
    command:
      - --build.cmd
      - "go build -o tmp/teleport -ldflags '-w -s' -tags 'webassets_embed' ./${TOOL_FOLDER}/teleport"
    networks:
      teleport:
        aliases:
          - go.teleport
          - dumper.go.teleport
    ports:
      - 3080:443
      - 3025:3025
      - 3023:3023
    volumes:
      - ../../teleport:/app/:rw,delegated
      - /app/tmp
      - ../data/cache/go-pkg:/go/pkg/mod:rw,delegated
      - ../data/cache/go:/root/.cache/go-build,delegated
      - ../data/teleport:/var/lib/teleport
      - ../build/.air.toml:/app/.air.toml
      - ../teleport/teleport.yaml:/etc/teleport.yaml
      - ${LICENSE_FILE}:/etc/license.pem
    environment:
      TELEPORT_UNSTABLE_VC_SYNC_ON_START: yes

networks:
  teleport:
