services:
  frontend:
    container_name: frontend
    build:
      dockerfile: ../development/frontend/Dockerfile
      context: ../../teleport
      target: node-dependencies
    working_dir: ${VITE_CONFIG_DIRECTORY}
    command: node /app/node_modules/.bin/vite --config ${VITE_CONFIG_DIRECTORY}/vite.config.ts
    networks:
      - teleport
    ports:
      - 443:3000
    volumes:
      - ../../teleport/web/:/app/web/
      - ../../teleport/gen/proto/js/:/app/gen/proto/js/
      - ../../teleport/e/web/:/app/e/web/
      - ../certs:/app/certs:ro
      - ../data/cache/frontend:/webpack/cache:rw,delegated
    environment:
      NODE_OPTIONS: --max-old-space-size=8192
      VITE_TARGET: go.teleport:443
      VITE_HTTPS_CERT: /app/certs/server.crt
      VITE_HTTPS_KEY: /app/certs/server.key

  node:
    build:
      dockerfile: development/build/Dockerfile
      context: ../..
      target: static
      args:
        TOOL_FOLDER: ${TOOL_FOLDER}
    networks:
      - teleport

  go.teleport:
    container_name: go.teleport
    hostname: go.teleport
    build:
      dockerfile: development/build/Dockerfile
      context: ../..
      target: live-reload
      args:
        TOOL_FOLDER: ${TOOL_FOLDER}
    command:
      - --build.cmd
      - "go build -o tmp/teleport -ldflags '-w -s' -tags 'webassets_embed' ./${TOOL_FOLDER}/teleport"
    networks:
      teleport:
        aliases:
          - go.teleport
          - dumper.go.teleport
    ports:
      - 3080:443
      - 3025:3025
      - 3024:3024
      - 3023:3023
    volumes:
      - ../../teleport:/app/:rw,delegated
      - ../../teleport/webassets/:/app/webassets/
      - /app/tmp
      - ../data/cache/go-pkg:/go/pkg/mod:rw,delegated
      - ../data/cache/go:/root/.cache/go-build,delegated
      - ../data/teleport:/var/lib/teleport
      - ../build/.air.toml:/app/.air.toml
      - ../teleport/teleport.yaml:/etc/teleport.yaml
      - ${LICENSE_FILE}:/etc/license.pem
    environment:
      TELEPORT_UNSTABLE_VC_SYNC_ON_START: yes

networks:
  teleport:
